# This file describes the alternative machine learning models
# available to InvokeAI script.
#
# To add a new model, follow the examples below. Each
# model requires a model config file, a weights file,
# and the width and height of the images it
# was trained on.
stable-diffusion-1.5:
  description: The newest Stable Diffusion version 1.5 weight file (4.27 GB)
  weights: ./models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
  default: true
inpainting-1.5:
  description: RunwayML SD 1.5 model optimized for inpainting (4.27 GB)
  weights: ./models/ldm/stable-diffusion-v1/sd-v1-5-inpainting.ckpt
  config: ./configs/stable-diffusion/v1-inpainting-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
  stable-diffusion-1.5:
stable-diffusion-1.4:
  description: The original Stable Diffusion version 1.4 weight file (4.27 GB)
  weights: ./models/ldm/stable-diffusion-v1/sd-v1-4.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
waifu-diffusion-1.3:
  description: Stable Diffusion 1.4 fine tuned on anime-styled images (4.27)
  weights: ./models/ldm/stable-diffusion-v1/model-epoch09-float32.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
hassan-nsfw:
  description: Hassan's blend 1.3
  weights: ./models/HassansBlend1.3.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
hassan-candy-mission:
  description: Hassan's Candy Mission Berry
  weights: ./models/ldm/stable-diffusion-v1/CandyMissionBerryF222-hassan.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
berry-mix:
  description: Berry Mix
  weights: ./models/ldm/stable-diffusion-v1/berrys-mix.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
ghibli:
  description: Ghibli Mix
  weights: ./models/ldm/stable-diffusion-v1/StudioGhibliV4.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
easter:
  description: easter epoc 9
  weights: ./models/
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
floats-mix:
  description: Floats Mix
  weights: ./models/float's-mix.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
hiten:
  description: Hiten's 8k wallpaper
  weights: ./models/Hiten girl_anime_8k_wallpaper_4k.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
kl-f8-anime:
  description: kl-f8-anime2
  weights: ./models/kl-f8-anime2.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
latex:
  description: latex
  weights: ./models/latex-artist-art.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
microworlds:
  description: microworld_PublicPrompts.ckpt
  weights: ./models/microworld_PublicPrompts.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
mmd:
  description: mmd-1-18-model-merge-toned-alpha.ckpt
  weights: ./models/mmd-1-18-model-merge-toned-alpha.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
model-epoch-9:
  description: model epoch 9 float 32
  weights: ./models/model-epoch09-float32.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
mo-di:
  description: mo-di pruned v1
  weights: ./models/moDi-v1-pruned.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
pachu:
  description: pachu erotic artist style
  weights: ./models/pachu_artwork_style_v1_iter8000.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
samdoesart-style:
  description: samdoesart style
  weights: ./models/samdoesarts_style.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
trinart2:
  description: trinart2_step115000.ckpt
  weights: ./models/trinart2_step115000.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
comics-diffusion:
  description: Comics Diffusion
  weights: ./models/comic-diffusion-V2.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
calarts:
  description: Calarts Style
  weights: ./models/CALARTS.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
complex-line-art:
  description: "Style of Complex Line Art"
  weights: ./models/complex-lineart-style.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
sxd:
  description: sxd v0.7
  weights: ./models/sxd-v0.7-pruned.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
unnamed-model:
  description: Unnamed Model
  weights: ./models/unnamed-model.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
everything:
  description: Anything+HenDiff_RD1212+Lokean_Missionary_POV+pyros-bj-v10.7+ F222 0.35
  weights: ./models/supermix.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
pyros-bj:
  description: pyros bj model 1.0
  weights: ./models/pyros-bj-v1-0.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
delphine:
  description: youtube thirst trap
  weights: ./models/belle-2.5.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
degenerate:
  description: The Definitive Degenerate Modelv0.2+SD1.4.ckpt
  weights: ./models/The Definitive Degenerate Modelv0.2+SD1.4.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
cafe-instagram:
  description: instagram
  weights: ./models/cafe-instagram-unofficial-test-epoch-9-140k-images-fp32.ckpt
  config: ./configs/stable-diffusion/v1-inference.yaml
  width: 512
  height: 512
  vae: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
